#!/usr/bin/perl

=pod

=head1 NAME

gwbn - goto window by name

=head1 SYNOPSIS

gwbn is a program that goes to a window by name 

=cut

use strict;

use Gtk2 -init;
use Gnome2::Wnck;
use Data::Dumper;
use Getopt::Std;
use lib 'lib';
use Gwbn;

our %opts;

getopts("vlh",\%opts);
my $regex = shift;


if($opts{h} or (!$opts{l} and !$regex)) {
    usage();
    exit(5);
}

sub usage {
    print <<END;
Usage: gwbn [options] <regex>

Options:
    -h       : display help
    -v       : verbose
    -l       : list window names only
END
}

if ($opts{l}) {
    $regex = "";
}

my @matches = window_matches($regex);
if (not $opts{l}) {
    if (scalar(@matches)) {
        goto_window(@matches[0]);
        exit 0;
    } else {
        print "Can't find a window that matches '$regex'\n";
        exit 1;
    }
} else {
   print map {$_->get_name . "\n"} @matches;
   exit 0;
} 
