#!/usr/bin/perl
use strict;

use Gtk2 -init;
use Gnome2::Wnck;
use Data::Dumper;

my $match = shift || "no such window";

my $screen = Gnome2::Wnck::Screen->get_default();
$screen->force_update();


# print Dumper($screen);
# print Dumper($screen->get_windows);
my @windows = $screen->get_windows;
foreach my $win (@windows) {
    print $win->get_name, "\n";
    if ($win->get_name =~ /$match/) {
        print "\tWould match!\n";
        $win->get_workspace->activate(time);
        $win->activate(time);
        exit 0;
    }
}

exit 1;
#print $screen->get_number;
#print "\n";
#my $workspace = ($screen->get_workspaces)[0];
#$workspace->activate(time + 2);


# $screen->force_update();
