#!/usr/bin/perl

=pod

=head1 NAME

gwbn - goto window by name

=head1 SYNOPSIS

gwbn is designed to goto a window by name in a Linux / Gnome
environment.  It is inspired on a tool that I had back with the ion
window manager that would do the same thing.  gwbn takes a regular
expression on the command line and changes workspaces, and activates
the target window, for the first window that matches.

Example:

 gwbn emacs

Will take you to your emacs window.

=head1 AUTHOR

Sean Dague E<lt>sean@dague.netE<gt>

=head1 LICENSE

gwbn is released under the MIT license.  See COPYING for more details.

=cut

use strict;

use Data::Dumper;
use Getopt::Std;
use lib 'lib';
use Gwbn;

our %opts;

getopts("vlh",\%opts);
my $regex = shift;


if($opts{h} or (!$opts{l} and !$regex)) {
    usage();
    exit(5);
}

sub usage {
    print <<END;
Usage: gwbn [options] <regex>

Options:
    -h       : display help
    -v       : verbose
    -l       : list window names only
END
}

if ($opts{l}) {
    $regex = "";
}

my @matches = window_matches($regex);
if (not $opts{l}) {
    if (scalar(@matches)) {
        goto_window(@matches[0]);
        exit 0;
    } else {
        print "Can't find a window that matches '$regex'\n";
        exit 1;
    }
} else {
   print map {$_->get_name . "\n"} @matches;
   exit 0;
} 
